### ISSUE TITLE
代码中centerness的疑问

### ISSUE THREAD

**Issue by kuang-linyi** [xuannianz/keras-fcos#3]
作者，您好。
      在学习您的代码中，我遇到了一个疑问。centerness的实现代码一直没有找到，希望您能给予提示。

**Comment by xuannianc** [comment]
你好，是这一部分吗？
https://github.com/xuannianz/keras-fcos/blob/ee6546d9907ce829388097a4fa359e2d2a3f2045/generators/generator.py#L496-L497

**Comment by kuang-linyi** [comment]
好的，就是这一部分。真是谢谢您了
