### ISSUE TITLE
train with default parameters?

### ISSUE THREAD

**Issue by VectXmy** [xuannianz/keras-fcos#5]
batchsize=1?lr=1e-4?steps=500k?
Did you train with default parameters of keras-retinanet?

**Comment by xuannianz** [comment]
No, I set batch_size=1, steps=15000 and init lr=1e-4. LR will decay to 1e-5 and 1e-6 when finetune.

**Comment by VectXmy** [comment]
How long did the training take😂

**Comment by xuannianz** [comment]
It depends on your gpu. It takes 2080ti a dozen hours.
